### ISSUE TITLE
Users should get feedback on calls that are rejected by estimateGas

### ISSUE THREAD

**Issue by satello** [kleros/kleros-juror-front#10]
An example is trying to activate tokens when you have none. You can still input the amount and push submit and then nothing happens. I would assume because `estimateGas` stops the API from making the call but there is no feedback for the user so it just looks like it isn't working.

**Comment by epiqueras** [comment]
I think the API should throw and the UI should catch the error and display
it.

**Comment by epiqueras** [comment]
Depends on kleros/kleros-api#107
