### ISSUE TITLE
Only show 3 decimals on the amount of PNK and round it to the nearest value

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-juror-front#111]
Otherwise people wonder why they don't have the exact value.

**Comment by epiqueras** [comment]
@satello, @federicoast deposited exactly `1000`. Why would the API make that 999.999...?

**Comment by clesaege** [comment]
I guess the API converts it to a float.

**Comment by satello** [comment]
Didn't we see something like this before @epiqueras? It is just being converted from wei to eth units with web3 in the api. With a whole number like that it is odd that it would get a rounding error

**Comment by clesaege** [comment]
There is also a rounding error leading to this: https://github.com/kleros/kleros-juror-front/issues/112

**Comment by epiqueras** [comment]
@satello I can't recall. I'm guessing that whatever fixes #112 will fix this too.

**Comment by satello** [comment]
I can't reproduce either of these. My whole numbers never get rounded. Can you add some logs on your end @epiqueras to try to pin down exactly where it is coming from?

**Comment by epiqueras** [comment]
@satello I haven't experienced this either.
