### ISSUE TITLE
Deadlines are not displayed on disputes table

### ISSUE THREAD

**Issue by satello** [kleros/kleros-juror-front#12]
All dispute deadlines are currently 'None' in the table

**Comment by epiqueras** [comment]
That means the API is not returning them.

**Comment by epiqueras** [comment]
@satello 
This is because no appeal in `appealJuror` has `canRule: true`. So I think it's an API issue.

**Comment by epiqueras** [comment]
Caused by kleros/kleros-api#108

**Comment by satello** [comment]
@epiqueras even if `canRule` is not true a deadline can still be shown. All appeals have deadlines regardless of ability to rule or not

**Comment by epiqueras** [comment]
True. I was thinking of a deadline for the juror. Since he can’t rule, he
doesn’t have a deadline.

But you are right, we should show it anyway.

I’ll change it.
