### ISSUE TITLE
Improve iteration

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-juror-front#5]
To avoid iterating everytime on all the disputes.
Look at those events:
https://github.com/kleros/kleros/blob/master/contracts/KlerosPOC.sol#L534
https://github.com/kleros/kleros-interaction/blob/master/contracts/standard/arbitration/Arbitrator.sol#L61

raised within a session timeframe.
From them we can get a list of disputeID and only look at those.

**Comment by epiqueras** [comment]
Let's move this to `kleros-api`.
