### ISSUE TITLE
Duplicate notification in juror panel

### ISSUE THREAD

**Issue by federicoast** [kleros/kleros-juror-front#60]
https://drive.google.com/open?id=1cev-Fx1LCQ52DLGZLNaknZLXXWYvCcKt

See that I got 2 notifications about the exact same event of “Dispute 60: Tokens have been redistributed”.

I should only get one notification for this.

**Comment by satello** [comment]
This is because if you had more than one vote there was more than one token distribution for you. So it is working as expected
