### ISSUE TITLE
Remove file name

### ISSUE THREAD

**Issue by federicoast** [kleros/kleros-juror-front#62]
https://drive.google.com/open?id=1mtPA_Q1lrLlyb-Xz1r4PCegMBIyrtdiL

We should remove the name of the file (https://staging-doges-on-trial). It’s not necessary to show that. From the point of view of the user, it looks like an error.

**Comment by epiqueras** [comment]
@clesaege Is this OK from the transparency side of things?

**Comment by clesaege** [comment]
Yeah, users are supposed to trust their interface.

**Comment by epiqueras** [comment]
Ok

**Comment by epiqueras** [comment]
Closed in https://github.com/kleros/kleros-juror-front/commit/f743f043a4a46c5f9bc45ffaa5d4f71c1a6b520e
