### ISSUE TITLE
Deposited pie blue area

### ISSUE THREAD

**Issue by federicoast** [kleros/kleros-juror-front#67]
https://drive.google.com/open?id=1y6IB-YRmqccy2TBxOZsBEm91BFQShlIc

Now, the “amount of blue” in the pie represents the percentage of PNK the user deposited in the subcourt out of his total PNK holdings. I think that this is a bit confusing.

Maybe the pie should only have 2 states:

-Empty (no PNK were deposited)
-Full (PNK were deposited)

**Comment by epiqueras** [comment]
That's what makes a pie chart a pie chart, what do you confuse it for?

**Comment by federicoast** [comment]
I thought that the amount of blue in the pie chart was the % of PNK I deposited out of the total PNK deposited in the subcourt.

I think most users will make the same interpretation.

**Comment by epiqueras** [comment]
Those two things are the same, PNK deposited === PNK deposited in the sub
court. That would always be 100%.

The logical interpretation is percentage deposited out of total PNK owned.

**Comment by epiqueras** [comment]
The explainer makes it clearer now.
