### ISSUE TITLE
Change in wording: Party A vs. Party B

### ISSUE THREAD

**Issue by federicoast** [kleros/kleros-juror-front#68]
https://drive.google.com/open?id=1AG6v7jzLVBMtNG0LcoIVKtxpjBuFHbfr

I think it's better to replace "Party A" by "Submitter" and "Party B" by "Prosecutor" to make it coherent with the words we are using in the pilot.

**Comment by epiqueras** [comment]
@clesaege We were using `Submitter` and `Challenger`, can we still change the meta evidence for this?

**Comment by satello** [comment]
We can change the meta-evidence but Submitter and Challenger have to map to something. I guess they could both just map to empty strings

**Comment by epiqueras** [comment]
They should map to `null`.

**Comment by clesaege** [comment]
We don't even needs "Votes for party A" or "Vote for party B". We can just count "Yes" and "No".

**Comment by epiqueras** [comment]
Yeah, use rulingTitles in meta evidence.
