### ISSUE TITLE
Better structure for the "ruling section".

### ISSUE THREAD

**Issue by federicoast** [kleros/kleros-juror-front#69]
https://drive.google.com/open?id=1AG6v7jzLVBMtNG0LcoIVKtxpjBuFHbfr

This could be a bit complicated to implement before the launch, but if we can't do it now, we could do it a bit later.

Does the Image Show a Doge?

The decision of the jury was NO. The PROSECUTOR won the case.

You voted for the SUBMITTER.
Juror 2 voted for the PROSECUTOR.
Juror 3 voted for the PROSECUTOR.

Your vote was INCOHERENT with the majority. As a result, you lost X PNK.

(Here we could add some link saying "_How is this calculated?_” This could link to a Medium post explaining that).

**Comment by epiqueras** [comment]
What is the point of showing Juror 1 voted X, Juror 2 voted X, etc, if they are anonymous? Isn't showing the total votes for each side better?

**Comment by federicoast** [comment]
Either solution is good. I'm just thinking of a way for the juror to better understand how the coherent/incoherent thing works and how it affects PNK distribution.

**Comment by epiqueras** [comment]
We need to start working on the knowledge base for things like this that we need to link to. We already have https://crisp.chat/en/knowledge/
