### ISSUE TITLE
Give better gas estimation for transfer to contract

### ISSUE THREAD

**Issue by clesaege** [kleros/kleros-juror-front#76]
Currently, the interface asks to put more than 6 000 000 gas. We can change it to 200000

**Comment by clesaege** [comment]
The proposed amount of price of 1GWei is too low. We need to have an estimation of what it takes.

**Comment by epiqueras** [comment]
@satello This is on the API.

**Comment by epiqueras** [comment]
Opened kleros/kleros-api#161
